# .github/workflows/metrics.yml
name: Metrics
on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: YOUR_USERNAME
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
